### ISSUE TITLE
/graphql endpoint error for multisite subfolder install

### ISSUE THREAD

**Issue by charlesmulder** [wp-graphql/wp-graphql-acf#87]
I have a WordPress multisite subfolder installation. Been making site specific queries using the following endpoint convention `site1.com/graphql` and `site1.com/site2/graphql`. 

When I network activate `wp-graphql-acf` I get the following error when accessing `site1.com/site2/graphql`, but `site1.com/graphql` is still working. 

```php
Fatal error: Uncaught Error: Class 'WPGraphQL\TypeRegistry' not found in /var/www/html/wp-content/plugins/wp-graphql-acf-0.3.0/src/class-config.php:629 

Stack trace: 
#0 /var/www/html/wp-content/plugins/wp-graphql-acf-0.3.0/src/class-config.php(180): WPGraphQL\ACF\Config->register_graphql_field('post', 'slider', Array) 
#1 /var/www/html/wp-content/plugins/wp-graphql-acf-0.3.0/src/class-config.php(32): WPGraphQL\ACF\Config->add_acf_fields_to_post_object_types() 
#2 /var/www/html/wp-includes/class-wp-hook.php(286): WPGraphQL\ACF\Config->init(Object(WPGraphQL\Registry\TypeRegistry)) 
#3 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) 
#4 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) 
#5 /var/www/html/wp-content/plugins/wp-graphql-0.4.0/src/Registry/TypeRegistry.php(316): do_action('graphql_registe...', Object(WPGraphQL\Registry\TypeRegistry)) 
#6 /var/www/html/wp-includes/class-wp-hook.php(286): WPGraphQL\Registry\TypeRegistry->WPGraphQL\Registry\{closure}(Object(WPGraphQL\R in /var/www/html/wp-content/plugins/wp-graphql-acf-0.3.0/src/class-config.php on line 629
```

As far as I can tell the namespace declared at the top of the file should be 

```php
// use WPGraphQL\TypeRegistry;
use WPGraphQL\Registry\TypeRegistry;
```
Changing the namespace introduced a new error:

```
Fatal error: Uncaught Error: Using $this when not in object context in /var/www/html/wp-content/plugins/wp-graphql-0.4.0/src/Registry/TypeRegistry.php:466 
Stack trace: 
#0 /var/www/html/wp-content/plugins/wp-graphql-acf-0.3.0/src/class-config.php(629): WPGraphQL\Registry\TypeRegistry::get_type('post_Slider') 
#1 /var/www/html/wp-content/plugins/wp-graphql-acf-0.3.0/src/class-config.php(180): WPGraphQL\ACF\Config->register_graphql_field('post', 'slider', Array) 
#2 /var/www/html/wp-content/plugins/wp-graphql-acf-0.3.0/src/class-config.php(32): WPGraphQL\ACF\Config->add_acf_fields_to_post_object_types()
#3 /var/www/html/wp-includes/class-wp-hook.php(286): WPGraphQL\ACF\Config->init(Object(WPGraphQL\Registry\TypeRegistry)) 
#4 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) 
#5 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) 
#6 /var/www/html/wp-content/plugins/wp-graphql-0.4.0/src/Registry/TypeRegistry.php(316): do_action('graphql_registe...', Object(WPGraphQL\Registry\Type in /var/www/html/wp-content/plugins/wp-graphql-0.4.0/src/Registry/TypeRegistry.php on line 466
```
As far as I can tell `WPGraphQL\Registry\TypeRegistry::get_type()` isn't a static function

```php
# https://github.com/wp-graphql/wp-graphql-acf/blob/v0.3.0/src/class-config.php#L431
if ( TypeRegistry::get_type( $field_type_name ) == $field_type_name ) {

# https://github.com/wp-graphql/wp-graphql/blob/v0.4.0/src/Registry/TypeRegistry.php#L465
public function get_type( $type_name ) {
```
I must be missing something, cause I see alot of calls to `TypeRegistry::get_type()`. 

Would appreciate if someone could enlighten me?

**Comment by charlesmulder** [comment]
This issues seems to be resolved on the latest `develop` branch. So, `wp-graphql-acf` version `0.3.0` is not compatible with `wp-graphql` version `0.4.0`. 

`wp-graphql-acf` should be at a higher version, which at the moment is the `develop` branch.

**Comment by jasonbahl** [comment]
@charlesmulder there was an issue with the v0.3.0 tag on Packagist. I've pushed a minor v0.3.1 and I believe it should be good now. Let me know if that's not the case.

**Comment by charlesmulder** [comment]
Sorted. Thanks.
